# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
        - FRONT_URL=http://localhost:3000
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app